### ISSUE TITLE
Saved Particle Lists are written in angstroms and not pixels

### ISSUE THREAD

**Issue by dmichalak** [FrangakisLab/ArtiaX#1]
Importing a Particle List created in 3dmod (.mod) is displayed correctly on the tomogram file loaded into ArtiaX. However, when saving the Particle List as a new .mod file, the coordinates are scaled by the Angstrom/pixel value. This was confirmed by comparing the coordinates written by IMOD's `model2point` on the .mod file generated by 3dmod and the saved .mod file from ArtiaX: 

`$ model2point 3dmod.mod model2point_3dmod.coords`
`$ head -n 1 model2point_3dmod.coords`
`     551.33      966.00      317.00`

`$ model2point ArtiaX.mod model2point_ArtiaX.coords`
`$ head -n 1 model2point_chmx.coords`
`     4774.55     8365.56     2745.22`

For this data, there is 8.66 Angstroms/pixel.

**Comment by FrangakisLab** [comment]
Hi, thanks for the report. It seems I didn't run into a model file with a pixel size specified while testing this (I used rather old files from the PEET example datasets).

I looked into the model format again, and there is both a scaling factor for x, y and z and a pixel size defined. I've committed a solution now in the [development branch](https://github.com/FrangakisLab/ArtiaX/tree/devel_release), which reads the pixel size and scaling factors and computes a final (isotropic) pixel size in angstrom. This is then set as the scale factor for particle origins in the "Select/Manipulate" tab. 

Saved coordinates will be in pixels, and the pixelsize will be set to x_scale*pixelsize with units of Angstrom. Is this an acceptable solution? 

You can try it using the attached build (extract the wheel file before installing). I'm still working on finding a way to set up daily builds.

[ChimeraX_ArtiaX-0.2a1-py3-none-any.zip](https://github.com/FrangakisLab/ArtiaX/files/9254663/ChimeraX_ArtiaX-0.2a1-py3-none-any.zip)

**Comment by uermel** [comment]
Hi, thanks for the report. It seems I didn't run into a model file with a pixel size specified while testing this (I used rather old files from the PEET example datasets).

I looked into the model format again, and there is both a scaling factor for x, y and z and a pixel size defined. I've committed a solution now in the [development branch](https://github.com/FrangakisLab/ArtiaX/tree/devel_release), which reads the pixel size and scaling factors and computes a final (isotropic) pixel size in angstrom. This is then set as the scale factor for particle origins in the "Select/Manipulate" tab. 

Saved coordinates will be in pixels, and the pixelsize will be set to x_scale*pixelsize with units of Angstrom. Is this an acceptable solution? 

You can try it using the attached build (extract the wheel file before installing). I'm still working on finding a way to set up daily builds.

[ChimeraX_ArtiaX-0.2a1-py3-none-any.zip](https://github.com/FrangakisLab/ArtiaX/files/9254663/ChimeraX_ArtiaX-0.2a1-py3-none-any.zip)

**Comment by dmichalak** [comment]
Yes, that sounds good! Apologies for the daily in response. I apparently didn't set up notifications correctly to see when there was a reply to this.
