### ISSUE TITLE
Rotate Selected not working in ChimeraX 1.7

### ISSUE THREAD

**Issue by RHennellJames** [FrangakisLab/ArtiaX#9]
In ChimeraX 1.6/ArtiaX 0.3, when "Rotate Selected" was active, dragging with the right mouse button near the centre of the screen rotated the particle around the x and y axes of the user view and dragging with the right mouse button at the edge of the screen rotated the particle around the z axis of the user view. In ChimeraX 1.7/ArtiaX 0.3 even if I drag at the very edge of the view I can only rotate in x and y. This makes it very difficult to correctly orient particle axes in the tomogram plane.

Dragging at the edge of the screen still rotates around z when the normal ChimeraX Right Mouse/Rotate Model is active, so I think this is an ArtiaX-specific issue.

For now I have gone back to ChimeraX 1.6

**Comment by uermel** [comment]
Hi @RHennellJames, this should be fixed in the latest release! 

You should now be able to use the mouse modes as before.

**Comment by RHennellJames** [comment]
Hi @uermel, 
Unfortunately this doesn't seem to have solved the issue. In ChimeraX 1.6/Artiax 0.3 when I drag with the right mouse button at the edge of the screen the particle rotates about the z axis of the screen (not the z axis of the particle). In ChimeraX 1.7/Artiax 0.4.1 dragging with the right mouse button at the edge of the screen still rotates the particle around the x or y axes of the screen. It doesn't seem to be possible to rotate the particle around the screen z axis with Rotate Selected Particles anymore.

When I select another object (e.g. a PDB structure) in ChimeraX 1.7 and set _ui mousemode right "rotate selected models"_, dragging with the right mouse button still rotates the object around the z axis of the screen. I think there must have been a change in ChimeraX 1.7 that affects whatever function ArtiaX uses for _ui mousemode right "rotate selected particles"_.

I am trying to select proteins in a membrane and then rotate the particle so the z axis of the particle is normal to the membrane and therefore parallel to the plane of the tomogram (because the membrane is parallel to the plane of the tomogram). I found the easiest way to do this is to rotate about x or y so the z arrow of the particle is in the tomogram plane and then rotate about the z axis until the z arrow points in the right direction. With ChimeraX 1.7 neither Artiax 0.3 or Artiax 0.4.1 allows this.

**Comment by uermel** [comment]
Hi @RHennellJames, thank you for the quick feedback. Indeed, I forgot to include a fix prepared by Deborah, a new contributor. 

This behavior is now available again: 
https://github.com/FrangakisLab/ArtiaX/assets/6641113/7cf025fd-edb0-454e-b600-308643e1e2e6

Is that what you are looking for?

**Comment by RHennellJames** [comment]
Hi @uermel,

Yes that fixed it. Thanks for updating so quickly!
